server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/precificacao?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: atilalavor
    password:
  jpa:
    show-sql: true #ver sql no terminal
    hibernate:
      ddl-auto: update #drop => apaga todo banco quando roda app
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
