server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/precificacao?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: atilalavor
    password:
  jpa:
    show-sql: true #ver sql no terminal
    hibernate:
      ddl-auto: update #drop #create => apaga todo banco quando roda app
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  boot:
    admin:
      client:
        url: "http://127.0.0.1:8080"


logging:
  level:
    org:
      hibernate:
        type: trace

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"







